### PR TITLE
Handle no value being given to dumpvar

### LINKED ISSUE #633: Handle dumpvar being given 0 arguments
This may happen as a result of a call to a function that returns nothing, so returning "none" instead of erroring is probably better behaviour.

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by well-in-that-case** [comment]
Do you think someone would accidentally confuse this with a string being "none"? Someone could overlook this at a glance.

**Comment by Sainan** [comment]
There is a very clear difference:
image

The only thing is that "none" is not a type name the typical Lua dev might be familiar with. Maybe "void" would be better? I guess it should because even our own type hints do call this "void".

**Comment by well-in-that-case** [comment]
Users will know that dumpvar specifies the length of the string, but my point is despite that I can see someone not realizing it esp. if they haven't used dumpvar much. It would be that type of programming mistake where it was in plain sight the whole time. Such that it's not new knowledge, you just overlooked something. Perhaps `none (dumpvar got no value)`

**Comment by Sainan** [comment]
Or just `(no value)`?

**Pull request merged**
