### PR TITLE
Fix intrinsics detection

### PR DESCRIPTION
**Pull request by asumbek**
This commit is related to patches in the plutolang Termux, and it should be upstreamed to Pluto repository.
- https://github.com/termux/termux-packages/blob/master/packages/plutolang/intrin-detection.patch
- https://github.com/termux/termux-packages/blob/master/packages/plutolang/intrin-patch.patch

### CODE REVIEW

**Comment by Sainan** [comment]
I'm confused what the issue even is. Is `getauxval` not available on your device? I verified it compiled and ran just fine on my Pixel 5.

**Comment by asumbek** [comment]
It doesn't available in target Android armv7l, it returns an undefined symbol.

**Comment by Sainan** [comment]
I don't think that should be the case since `getauxval` is an operating system API, so not tied to the CPU architecture. Is it possible that your issue is related to compiling on a 32-bit ARM CPU?

**Comment by Sainan** [comment]
Ah, actually I see now that `HWCAP_AES` et al are only defined on aarch64.

**Comment by Sainan** [comment]
https://github.com/calamity-inc/Soup/commit/68bdb501aee95827c476a5683ffe456fd1683f3b should probably fix this.

Really don't wanna do much 32-bit support esp. for a relatively new ISA, but I guess it just won't die.

**Pull request closed without merging**
