### PR TITLE
Update error functions to be [[noreturn]]

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by well-in-that-case** [comment]
Originally, this was not implemented because it confused GCC's implicit fallthrough warnings, and some functions would use different semantics of 'not returning', per se. This occurs around the specialized error handling with functions such as error_expected, but really in any case where 'throwerr' is called as the sole statement to a switch block. 

What are the reasons to use [[noreturn]] over the l_noret macro? Or rather, if it only applies to situations without this logic then it's fine.

**Comment by Sainan** [comment]
Having this avoids the compiler possibly making bad assumptions, which I have had happen working with Lua via C++.

This commit compiled perfectly with MSVC & Clang. I have no idea about GCC, but semantically calling a noreturn function is like using throw; you might be experiencing a compiler bug if it causes warnings.

I wasn't aware of the l_noret macro, but given that this project is moving toward C++ifying the Lua codebase, I think using C++ builtins that have meanings is much preferable to unused and meaningless macros.

**Comment by Sainan** [comment]
Okay, I see l_noret is not unused... if you want I could remove it and replace instances of it with [[noreturn]], would make it consistent.

**Comment by well-in-that-case** [comment]
> Okay, I see l_noret is not unused... if you want I could remove it and replace instances of it with [[noreturn]], would make it consistent.

I agree with the points you've made prior. Replacing l_noret with [[noreturn]] would be consistent. With the throwerr function, either break/return or [[fallthrough]] will need to be used in the switch/case statements (with 'throwerr') to avoid GCC's complaining. You can do this if you'd like, but I am also fine with doing it as well. This may be easier for me because I already have a GCC build environment set up.

Currently, I need to do a couple things IRL. Will be back for testing/merging later on.

**Comment by Sainan** [comment]
I will replace l_noret and push it to the noreturn branch, you can add fallthrough to suppress the GCC bug.

**Comment by well-in-that-case** [comment]
Looks good, seems like something in the full refactor over to [[noreturn]] corrected the GCC bug. Thanks for the PR, will merge.

**Pull request merged**
