### PR TITLE
Restrict walrus operator to only be used in if & while statements

### LINKED ISSUE #775: Call over active registers
The use of the walrus operator in `for ... in` loops will increase the active variables, but the next call does not account for them and can use the stack slots of these variables. This can result in a `Segmentation fault` when one of the variables is an upvalue and is used to remove the function from an active stack frame as is the case in the example with `c1` being removed due to an overlap with the active `x` upvalue.

```lua
local tmp
local function c1()
    tmp()
    error('')
end
function f()
    if tmp ~= nil then c1() end
    return 1, 2
end
local function bug(t)
    for a in x:=y:=t do
        tmp = function() x=nil end
    end
end
bug(f)
```

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by XmiliaH** [comment]
This seems to not fix the problem fully
```lua
local tmp

local function f()
    if tmp then
        tmp()
        error('')
    end
    return 1
end

while f() + a:=2 do
    tmp = function() a=nil end
end
```

**Comment by XmiliaH** [comment]
Can still read uninitialized variables:
```lua
local function read_uninit()
    if a:=2 then
    elseif b:=3 then
    end
    return b
end
do
    for k in pairs({}) do end
end

print(read_uninit())
```

**Comment by XmiliaH** [comment]
Should
```lua
if a:=false then
elseif b:=3 then
end
print(b)
```
print `nil`?

**Comment by Sainan** [comment]
Probably not, but in the name of not having UB, it will.

**Comment by XmiliaH** [comment]
I would even question if the scope of these should be smaller, the while case restricted to inside of the while body and for the if inside of the if body and the following elseif/else body.

**Comment by Sainan** [comment]
This might be slightly breaking, but I agree that the semantics of this make more sense.

**Comment by XmiliaH** [comment]
And for the `while` case I would expect the variable to be new on each iteration and not the same
```lua
local cnt=10
local function next()
    cnt=cnt-1
    if cnt == 0 then return false end
    return cnt
end

local table = {}
while a:=next() do
    table[#table+1] = ||->a
end
for k, v in ipairs(table) do
    print(v())
end
```

**Comment by Sainan** [comment]
I don't follow. It works as expected.

image

You are capturing local 'a', which obviously keeps being changed.

**Comment by XmiliaH** [comment]
Will break in

```lua
local tmp
local function c()
    if tmp then
        tmp()
        error('')
    end
    return 1
end

while a:=c() do
    tmp = ||->do a=nil end
end
```

**Comment by XmiliaH** [comment]
And to make it clearer. I would expect the loop
```lua
while a:=next() do body() end
```
to be translated to
```lua
while true do
   local a=next()
   if not a then break end
   body()
end
```
and not
```lua
local a
while true do
   a = next()
   if not a then break end
   body()
end
```

**Comment by XmiliaH** [comment]
I have no more complaints with the walrus operator.

**Pull request merged**
