### PR TITLE
Support compound XOR with '~='

### LINKED ISSUE #708: Compound XOR operator
I know `~=` is already inequality for expressions, and the lexer won't be able to tell the difference, but it should be unambiguous in the parser whether it's an expression or a statement.

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by well-in-that-case** [comment]
Seems cursed. Sure, this is technically a compound XOR, but it's also Lua's inequality operator. Being used as a statement does not read off well.

Take a snippet of Pluto code using this feature alone and show it to someone who knows Lua. They'll say "wtf". All of our new features perform a fairly obvious operation at first glance because we've implemented uncontroversial syntaxes that are essentially standardized between the popular programming languages nowadays.

**Comment by Sainan** [comment]
I think it's shit that they used `~` for both XOR and inequality (via `~=`), so this is a mistake we have to continue supporting now, but we shouldn't let that mistake drag us down, so if I want to quickly perform an XOR like this, I should be able to.

Why I think it's not a problem to introduce this:
1. Unambiguous to parse because of "statement vs expression" which already has tons of parsing differences in Pluto (class, switch).
2. XOR is rather rare. You'd only see this in "low level" code such as hash functions and protocols. I doubt this would be anyone's first look at Pluto code.
3. We already do offer `!=` so it would be perfectly possible for someone to be disciplined about their usage of `~=` vs `!=`.

**Comment by well-in-that-case** [comment]
The fact it's the same exact operator is the ambiguous part. Same operator, different meaning, different metamethods called. Ambiguities always have instances where they are clear, the whole point is that they can be easily confused for something else and this is a text-book example of that. 

And besides, cursed. I'd like a XOR compound operator, just not one that's exactly the same as the inequality operator. Unfortunately there are not many new operators suitable for this task, if any at all.

**Comment by Sainan** [comment]
It's not like this would be the first instance of the same token or keyword having different meanings depending on context:
- `:` is probably our worst offender with method calls, ternaries, and switch statement cases
- strings and tables don't just declare data, they can also initiate a function call
- `class` and `switch` have entirely different layouts and semantics depending on context (statement vs expression)

Also, I think it's fair to say that `!=` is the inequality operator for Pluto, because `~=` doesn't make a lot of sense for inequality, but it's a "supported for legacy reasons" kinda thing. — Not saying this is my opinion, but it's a way someone could look at Pluto, and it does match some of the Pluto code I've seen.

**Comment by well-in-that-case** [comment]
Switch statement cases is a well-agreed upon fault in our syntax so following through with that as precedent would be doubling down on an error. For the method syntax, the short-hand ternary provided substantial value over if then else. We've adopted imperfect syntax before so long as it provided a significant amount of value despite its flaws, exactly like how our compound operators don't support XOR. At best, this feature is neutral weight. The problem with neutral features is how they age. They can only go down, and something like this is a sensitive case which, to me, has a concerning probability of aging poorly.

**Comment by Sainan** [comment]
I don't really think the way we did switch statement cases is bad. It's exactly the same syntax everyone knows for them, and we made it work in Lua, with consideration for the ambiguities with the `:`. I think it works great, especially with the warning coverage.

This feature is certainly less problematic than that, because I don't see anyone making a mistake with this, so we wouldn't even need warnings to complement this syntax.

**Comment by data-man** [comment]
Will this break the compatibility with existing Lua scripts?

**Comment by Sainan** [comment]
No, existing Lua scripts only use `~=` as an expression. This just adds a meaning for it as a statement.

**Pull request merged**
