### PR TITLE
Disallow 'nil' as a default argument

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by well-in-that-case** [comment]
I'm not sure how much this would change esp. considering nil is technically already the default for any not-provided values.

**Comment by Sainan** [comment]
This is identical to writing `if arg == nil then arg = nil end` which is a no-op, but the instructions for it still must be generated.

**Comment by well-in-that-case** [comment]
Then couldn't you just ignore instances like this?

**Comment by Sainan** [comment]
I could, but code like this would suggest a fundamental misunderstanding of what default arguments are. They are a value to be assigned if the argument is nil. Someone may think it's a value to be assigned when the argument is absent, and they think they want to be explicit about an absent argument being nil. That's nonsense and I don't think it should be allowed.

**Pull request merged**
