### PR TITLE
Fix where -msha and -msse4.1 isn't recognized in non-x86_64

### PR DESCRIPTION
**Pull request by asumbek**

### CODE REVIEW

**Comment by Sainan** [comment]
Is this a hard compiler error for you? If so, under which circumstances did you encounter it?

**Comment by asumbek** [comment]
> Is this a hard compiler error for you? If so, under which circumstances did you encounter it?

Yes, and it's occured when using `g++`.
```
cd vendor/Soup/Intrin && make && cd ../..
make[4]: Entering directory '/home/komo/Projects/Pluto/src/vendor/Soup/Intrin'
g++ -std=c++17 -O3 -fvisibility=hidden -flto -c -Wall -msha -msse4.1 -c sha256_transform_intrin.cpp -o sha256_transform_intrin.o
g++: error: unrecognized command-line option '-msha'
g++: error: unrecognized command-line option '-msse4.1'
```
While `clang++` doesn't.
```
make[4]: Entering directory '/home/komo/Projects/Pluto/src/vendor/Soup/Intrin'
clang++ -c -Wall -msha -msse4.1 -c sha256_transform_intrin.cpp -o sha256_transform_intrin.o
clang++: warning: argument unused during compilation: '-msha' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
```

**Comment by Sainan** [comment]
On which platform?

**Comment by asumbek** [comment]
armv7l glibc Void Linux

**Comment by Sainan** [comment]
I unfortunately don't have any ARM machine other than the Mac. Pluto did work fine on Mac although I didn't try `make` on that.

My main concern with this patch is that `uname` is not available on Windows, but I guess neither is `g++` so it shouldn't be an issue.

**Comment by asumbek** [comment]
> My main concern with this patch is that `uname` is not available on Windows, but I guess neither is `g++` so it shouldn't be an issue.

It's possible for someone to build Pluto in MINGW/MSYS2 which provides `uname` and `g++`.

**Pull request merged**
