### PR TITLE
Add platform auto-detection

### LINKED ISSUE #846: Get rid of LUA_USE_{POSIX,_LINUX} macros
We can easily detect the platform via macros that are already provided by the compiler. Having to explicitly provide these macros is such a stupid pitfall, e.g. our PHP script builds do not set these, causing problems like failing to load C modules.

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by alerque** [comment]
Better make sure you're not loosing the ability to cross-compile while doing this. That's the usual pitfall of trying to do platform detection at compile time.

**Comment by Sainan** [comment]
Fair point, although I think it's not a huge concern, e.g. if you're on a Linux machine, you're not gonna be targeting Windows — I'm not sure that would even be possible.

And otherwise I do think the compiler should be setting the correct macros, e.g. if you're on a X86 machine targeting ARM64, MSVC would stop defining `_M_IX86` and start defining `_M_ARM64`.

**Comment by alerque** [comment]
Is is possible with Lua, that's why I thought to mention it. I build Lua interpreter binaries and various apps with Lua interpreters bundled into them targeting Windows from Linux all the time (see e.g. the luacheck.exe assets on LuaCheck project releases, those are all built on Linux).

**Comment by Sainan** [comment]
That's interesting. Do you think these changes would break your cross-compiling workflow?

**Pull request merged**
