### PR TITLE
Add table.find

### LINKED ISSUE #662: table.find
Similiar to table.filter, but returns the first matching entry. Useful for multi-dimensional tables.

```Lua
local menu = {
    { id = 1, name = "Apple" },
    { id = 2, name = "Banana" },
}
local item = menu:find(|item| -> item.id == 1)
print(item.name) -- Apple
```

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by well-in-that-case** [comment]
This function seems expressly intended to be used for a table of tables. This raises two concerns for me:
1. `find` is a very generic name, like that of `contains`. It's not really _finding_ an element.
2. Should this disallow types other than tables when looping? There seems to be no use for any non-table value.

While it technically offers elegance, I find this solution elegant too:
```lua
local menu = {
    { id = 1, name = "Apple" },
    { id = 2, name = "Banana" },
}
local item = menu:foreach(|item| -> do
    if item.id == 1 then
        return item
    end
end)
print(item.name) -- Apple
```
I'm not sure if this is something worth adding a one-liner because of cons aforementioned.

**Comment by Sainan** [comment]
It's a generic name for a generic operation. I think it's useful for quickly working with multi-dimensional tables, but it certainly can be used for other things, too:
```lua
local t = { 1, 2, 3, 4, 5 }
print(t:find(|x| -> x % 2 == 0)) --> 2
print(t:find(|x| -> x > 2)) --> 3
```

**Comment by well-in-that-case** [comment]
It can be used for other things, yes, but I don't know how useful that would be. And still, when my mind reads a function called `table.find`, I assume it's searching for an element. Perhaps `table.first`, such that it "returns the first value which passes the callback condition" as this obviously won't iterate beyond the first occurance, but this is only a pitch. Maybe `getfirst`, makes it more obvious it's getting the something.

**Comment by Sainan** [comment]
Well, I think my stated use-case of finding an element by a field in a multi-dimensional table would be the most common use-case where `first` would not be wrong, but might also be a bit misleading/counterintuitive.

**Comment by well-in-that-case** [comment]
The only confusion I can see regarding `first` would be that it returns the first element in the table or some shit, but then there is the callback argument. Which is why `getfirst` would clarify. I think it's implied that `first` or `getfirst` cannot hallucinate ordered non-array keys into a table.

**Comment by Sainan** [comment]
Well, now that you mention ordering, it makes me think that `first` is an even less optimal name to use. That name implies some guarantees about how multiple elements are handled, whereas this function simply assumes that you either know:
- The data you want is in the array-part and in the right order, or
- your filter-function uniquely identifies the element.

In the absence of these assumptions, it might also be `last`, `middle`, or `rabbitinthehat`.

**Comment by well-in-that-case** [comment]
Are there any other languages which implement functions like this? Perhaps we can take some inspiration.

**Comment by Sainan** [comment]
Javascript has Array.find that behaves exactly the same: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

Ruby calls this `detect`: https://stackoverflow.com/questions/2986852/ruby-detect-method

**Pull request merged**
