### PR TITLE
Disallow continue statement to jump into scope of locals

### LINKED ISSUE #792: Read of uninitialized variable
The `continue` statement will update `nactvarbeforecontinue`. This can happen in a nested scope with more active variables then the ones that will be visible in the `until` part, resurrecting previous dead variables and allowing to read uninitialized variables.

```lua
function read_uninit()
    local val
    repeat
        if val then
            local x, y, z
            continue
        end
    until (function() val=z return 1 end)()
    return val
end

do 
    local x, y
    for k in pairs({}) do end
end

print(read_uninit())
```

### PR DESCRIPTION
**Pull request by Sainan**
For repeat statement only.

### CODE REVIEW

**Comment by Sainan** [comment]
Tests failing, yay. Also realised another issue with this:
```lua
repeat
    if true then
        local a = ""
        continue
    end
    local a = 1
until a > 0 -- attempt to compare number with string
```

**Comment by XmiliaH** [comment]
Now
```lua
repeat
    local a = 1
    if true then
        continue
    end
until a > 0
```
is also disallowed.

**Comment by XmiliaH** [comment]
It seems to me that your issue works again

**Comment by Sainan** [comment]
I guess now that I fixed the `nactvarbeforecontinue` tracking, I could revert it so this is not an error, but I think it's better to keep it this way because it could be confusing otherwise:
```lua
repeat
    if false then
        local a = ""
        continue
    end
    local a = 1
until a > 0 -- attempt to compare number with nil
```

**Comment by XmiliaH** [comment]
First there is
```lua
repeat
    if true then
        local a = ""
        continue
    end
    local a = 1
    if false then continue end
until a > 0 -- attempt to compare number with string
```

**Comment by XmiliaH** [comment]
Sill has problems with
```lua
repeat
    if true then
        local a = ""
        do
            continue
        end
    end
    local a = 1
until a > 0 -- attempt to compare number with string
```

**Comment by XmiliaH** [comment]
That should fix it, but should the following piece of code work?
```lua
while true do
    repeat
        if true then
            continue 2
        end
        local a = 1
    until a > 0
end
```

**Comment by XmiliaH** [comment]
For now I do not see any further issues here.

**Pull request merged**
